name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Build with Gradlew
        run: ./gradlew clean build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Functional Tests
        run: ./gradlew check

      - name: Debug Secrets
        run: |
          echo "DOCKER_HUB_USERNAME is set: ${{ secrets.DOCKER_HUB_USERNAME != '' }}"
          echo "DOCKER_HUB_TOKEN is set: ${{ secrets.DOCKER_HUB_TOKEN != '' }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/demo-java:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/demo-java:latest

      - name: Configure Git credentials
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create Git Tag
        id: tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/}-$(date +%Y%m%d%H%M%S))"

      - name: Push Git Tag
        run: git tag ${{ steps.tag.outputs.tag }} && git push origin ${{ steps.tag.outputs.tag }}
